apiVersion: spec.keptn.sh/0.2.2
kind: "Shipyard"
metadata:
  name: "shipyard-job-exec"
spec:
  stages:
    - name: "hardening"
      sequences:
      - name: "miau"
        tasks:
        - name: "my-task"
